#!/bin/bash
#
# Sends data from STDIN to the Slack webhook
# configured in $SLACK_WEBHOOK_PATH
# which defauls to ~/config/slack.webhook
# 
# does not depend on the other scripts
# (i.e. can easily be reused in other projects)
# 
# The script can be given an argument describing
# the message severity. If one of the following
# values are given as the first argument, then
# an emoticon will be added to the start of
# the message to signal the severity:
# 
# - error
# - warn
# - info
# - success
# - debug
# - (empty)
# 
# By default no emoticon is added to the beginning.
# Emoticons can be added manually by inserting them
# in the text.
#
# The script can also be given a second argument to
# enable parsing of names and channels. Pass the
# string "link_names" as the second argument
# to enable this.
# 
# Examples:
# echo "message text" | ./slack
# echo ":grinning: hello" | ./slack
# echo "an error occured" | ./slack error
# echo "@channel this is an announcement" | ./slack info link_names
#

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$DEBUG" = "1" ]; then
    set -v
fi

if [ "$1" != "" ]; then
    STATUS="$1"
fi

if [ "$STATUS" = "error" ]; then
    STATUS=":red_circle: "
else
    if [ "$STATUS" = "warn" ]; then
        STATUS=":warning: "
    else
        if [ "$STATUS" = "info" ]; then
            STATUS=":information_source: "
        else
            if [ "$STATUS" = "success" ]; then
                STATUS=":white_check_mark: "
            else
                if [ "$STATUS" = "debug" ]; then
                    STATUS=":small_red_triangle: "
                else
                    STATUS=""
                fi
            fi
        fi
    fi
fi

if [ "$2" = "link_names" ]; then
    LINK_NAMES="1"
else
    LINK_NAMES="0"
fi

if [ "$SLACK_WEBHOOK_PATH" = "" ]; then
    SLACK_WEBHOOK_PATH="$HOME/.config/hubot-lyt/slack.webhook"
fi
if [ ! -f "$SLACK_WEBHOOK_PATH" ]; then
    echo "$SLACK_WEBHOOK_PATH does not exist; can't send message to Slack"
    exit
else
    SLACK_WEBHOOK="`cat "$SLACK_WEBHOOK_PATH" | head -n 1`"
fi

if [ "$ANNOUNCE_CHANNEL" = "" ]; then
    ANNOUNCE_CHANNEL="#webspiller"
fi

if [ "$BOT_NAME" = "" ]; then
    BOT_NAME="NLB"
fi

if [ "$BOT_ICON" = "" ]; then
    BOT_ICON="https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2015-08-10/8878694496_9e4e1c78db905c4d3396_48.jpg"
fi

JSON="{\"channel\": \"$ANNOUNCE_CHANNEL\", \"username\": \"$BOT_NAME\", \"icon_url\": \"$BOT_ICON\", \"link_names\": \"$LINK_NAMES\", \"text\": \"$STATUS$(cat /dev/stdin | sed 's/\(^\| \)\(http:[^ ]*\|https:[^ ]*\|[a-z][^ ]*\.[a-z][^ ]*\|[a-z][^ ]*\.[a-z][^ ]*\.[a-z][^ ]*\)\( \|$\)/\1<\2>\3/g' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk 1 ORS='\\n')\"}"
curl --silent -X POST --data-urlencode "payload=$JSON" "$SLACK_WEBHOOK" 2>&1 >/dev/null
