#!/bin/bash
#
# This script installs LYT to the test-server.
# By default, the most recent NLB-version is used.
#
# The script can optionally be given a specific tag,
# branch, or commit as the first argument to use instead.
#

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/common.sh"

COMMIT="$1"
message_info "Henter $COMMIT..."

repository_prepare

if [ "$COMMIT" = "" ]; then
    COMMIT="nlb-`git tag | grep "^nlb-[0-9\.]\+$" | sed 's/^.*-//' | sort -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 -g | tail -n 1`"
fi

# build
message_info "Kompilerer..."
cd $LYT_REPO
git checkout $COMMIT
npm install
cake clean
cake app

# install
mkdir -p "$DIR"/../target
rm "$DIR"/../target/www -rf
mv "$LYT_REPO"/build "$DIR"/../target/www

message_success "Installerte versjon '$COMMIT' av web-spilleren på test-serveren: http://`test_server_ip`/"
